# Site settings
title: Moon Shi Hyeon
description:
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Moon Shi Hyeon
user_description:
user_title: Hyeon
email: youngnam1009@hanmail.net
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
